"use client";

import React from "react";
import { Carousel, Card } from "@/components/ui/apple-cards-carousel";

export default function AppleCardsCarouselDemo() {
  const cards = data.map((card, index) => (
    <Card key={card.src} card={card} index={index} />
  ));

  return (
    <div className="w-full h-fit py-20 pb-0">
      <h2 className="max-w-7xl pl-4 mx-auto text-xl md:text-5xl font-bold text-neutral-800 dark:text-neutral-200 font-sans">
        Organize your creative workflow.
      </h2>
      <Carousel items={cards} />
    </div>
  );
}

const DummyContent = ({
  category,
  description,
  prompt,
}: {
  category: string;
  description: string;
  prompt: string;
}) => {
  return (
    <>
      <div className="bg-[#F5F5F7] dark:bg-neutral-800 p-8 md:p-14 rounded-3xl mb-4">
        <p className="text-neutral-600 dark:text-neutral-400 text-base md:text-2xl font-sans max-w-3xl mx-auto">
          <span className="font-bold text-neutral-700 dark:text-neutral-200">
            {category}: {description}
          </span>{" "}
          Store your best prompt engineering results in a secure vault. Never
          lose a perfect generation again. With Promptier, your creative journey
          is organized, searchable, and always at your fingertips.
        </p>

        <div className="mt-8 p-6 bg-white dark:bg-neutral-900 rounded-2xl border border-neutral-200 dark:border-neutral-700">
          <p className="text-sm font-semibold text-neutral-400 uppercase tracking-wider mb-2">
            The Prompt
          </p>
          <p className="text-neutral-800 dark:text-neutral-200 font-mono text-sm md:text-base leading-relaxed italic">
            &quot;{prompt}&quot;
          </p>
        </div>
      </div>
    </>
  );
};

const data = [
  {
    category: "Surrealism",
    title: "Dreamlike landscapes and impossible realities.",
    src: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop",
    content: (
      <DummyContent
        category="Surrealism"
        description="Explore the boundaries of imagination."
        prompt="A floating island with bioluminescent waterfalls cascading into a void of neon nebula clouds, high detail, surrealist oil painting."
      />
    ),
  },
  {
    category: "Cinematic",
    title: "Dramatic photorealism and professional lighting.",
    src: "https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=2574&auto=format&fit=crop",
    content: (
      <DummyContent
        category="Cinematic"
        description="Capture pure drama in every generation."
        prompt="Hyper-realistic portrait of an astronaut sitting on a park bench on Mars, Earth visible in the sky, dramatic side lighting, 8k resolution, cinematic color grading."
      />
    ),
  },
  {
    category: "Architecture",
    title: "Futuristic structures and urban dreamscapes.",
    src: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2670&auto=format&fit=crop",
    content: (
      <DummyContent
        category="Architecture"
        description="Design the cities of tomorrow."
        prompt="A solar-punk skyscraper made of glass and living vines, intricate balconies, futuristic city background, golden hour lighting, architecture photography."
      />
    ),
  },
  {
    category: "Digital Art",
    title: "Vibrant illustrations and conceptual designs.",
    src: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=2670&auto=format&fit=crop",
    content: (
      <DummyContent
        category="Digital Art"
        description="Craft unique styles and characters."
        prompt="A cyber-samurai standing in a rain-slicked Tokyo street, neon signs reflecting in puddles, vibrant purple and teal color palette, highly detailed digital illustration."
      />
    ),
  },
  {
    category: "Nature",
    title: "Breathtaking landscapes generated by AI.",
    src: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=2670&auto=format&fit=crop",
    content: (
      <DummyContent
        category="Nature"
        description="Bringing the beauty of the wild to your screen."
        prompt="A vast mountain range with turquoise lakes and crystalline peaks, misty atmosphere, sunset lighting, wide angle landscape photography."
      />
    ),
  },
  {
    category: "Minimalism",
    title: "Simple, clean, and elegant prompt engineering.",
    src: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=2670&auto=format&fit=crop",
    content: (
      <DummyContent
        category="Minimalism"
        description="The power of simplicity."
        prompt="A single lone tree on a perfectly flat field of snow, soft morning light, minimalist composition, Zen aesthetic, high contrast black and white."
      />
    ),
  },
];

